name: Build and Test

on: push

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build code
        run: ./gradlew build
      - name: Test code
        run: ./gradlew test
