name: Deploy Documentation

on:
  workflow_run:
    workflows: ["Build and Test"]
    branches: [main]
    types:
      - completed

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate docs
        run: ./gradlew :dokkaHtml

      - name: Bundle Docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs"

  deploy-docs:
    needs: generate-docs

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy docs
        id: deployment
        uses: actions/deploy-pages@v3
